# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'FirebaseUI', '~> 4.0'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'

  # Pods for SwiftChat

  target 'SwiftChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
